### ISSUE TITLE
Erro no DNS

### ISSUE THREAD

**Issue by TomCosta** [pythonbrasil/pybr2023-site#21]
O site apresenta erro no dns, mesmo tendo o CNAME configurado corretamente. Conseguiria dar um help? @rougeth Thanks!
**Erro:**
`This site can’t be reachedCheck if there is a typo in 2023.pythonbrasil.org.br.`
`DNS_PROBE_FINISHED_NXDOMAIN`

**Comment by rougeth** [comment]
✅ https://2023.pythonbrasil.org.br/

**Comment by TomCosta** [comment]
Opa legal! Como resolveu o problema? 😅

**Comment by rougeth** [comment]
O subdomínio `2023.` não existia no domínio :D
