### ISSUE TITLE
Layout do site

### ISSUE THREAD

**Issue by TomCosta** [pythonbrasil/pybr2023-site#28]
Precisamos do design para modificar o layout do site.
Se possível, marcar uma call para tirar dúvidas.
Atenciosamente,

**Comment by cecivieira** [comment]
@Buddhamaniac já te foi solicitado o layout para o site do evento?

**Comment by adrianomargarin** [comment]
https://xd.adobe.com/view/14dacec2-6cc8-4db3-ae0d-5ec3a8e5b377-4189/
